### ISSUE TITLE
data exploration | Highligted filters

### ISSUE THREAD

**Issue by camiplata** [gbif/hosted-portals#142]
We are deciding which filters to highlight, we have some preferred ones but to take this decision we wonder if GBIF has a list of the most used filters for downloads, this could help us all to identify user needs and highlight the right filters.

**Comment by tucotuco** [comment]
From the VertNet perspective the most common filters are, in descending
order taxonomic, geographic, institutionCode, basisOfRecord, hasTissue.
Within taxonomic and geographic there are some fields more popular than
others, but the hosted portals already support them (except county
explicitly).

**Comment by MortenHofft** [comment]
I do not have numbers for search, but for download it is typically a single taxon. possible with a country filter. Possible with a year filter. possible with a must-have-coordinates. 

You get a pretty good idea for the filters used by simply looking at a dataset. E.g. iNaturalist which is the most cited dataset.
https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7/activity

But aside from what users typically filter by, then there is the educational aspect that we also want to draw attention to some filters.  GBIF.org has occurrence status and license as the top filters, because we want to draw attention to these.

**Comment by MortenHofft** [comment]
I believe @jhnwllr analysed downloads at some point to generate a list of the most frequent filters?

https://data-blog.gbif.org/post/gbif-download-trends/ reference a previous post with download stats, but the link is dead http://www.johnwalleranalytics.org/2018/05/30/gbif-download-statistics/

**Comment by tucotuco** [comment]
> But aside from what users typically filter by, then there is the educational aspect that we also want to draw attention to some filters. GBIF.org has occurrence status and license as the top filters, because we want to draw attention to these.
> 
> But https://hp-theme.gbif-staging.org/data/ reflects what I would choose. Replacing country with GADM for a national site.

I feel strongly that the needs of different portals vary with respect to the need to promote filters. We (VertNet) very much want to have a configurable set of highlighted filters. (See also https://github.com/gbif/hosted-portals/issues/120, https://github.com/gbif/hosted-portals/issues/84).

**Comment by MortenHofft** [comment]
I believe this can be closed. If you need more, then please say so @camiplata
