### ISSUE TITLE
Updates not deploying?

### ISSUE THREAD

**Issue by langeveldNMR** [gbif/hosted-portals#172]
Earlier today there were some issues with Github and since then updates seem not to deploy to the portals. Or maybe I am doing something else wrong.

**Comment by MattBlissett** [comment]
In this case, the error was caused by a line in the _data/translations.yml file.  I've corrected it (see https://github.com/gbif/hp-nhm-rotterdam/commit/5b974c89b268b5ea64dcab1c064cc76228080ab9), using `\"` would also have worked.

The "Build passing" icon at https://github.com/gbif/hp-nhm-rotterdam#readme can change to "Build failing".  Clicking it gives the error output, although it's not necessarily easy to understand.
