### ISSUE TITLE
Pattern search used in "Recorded By" filter not rejected for Download

### ISSUE THREAD

**Issue by jholetschek** [gbif/hosted-portals#173]
Freetext filters are not supported for downloads and will be automatically removed.
If I use a pattern search for "recorded by", however, this doesn't happen. It seems to be working, but the resulting DwC archive is empty.

Examples:
https://www.gbif.org/occurrence/download/0343887-200613084148143
https://www.gbif.org/occurrence/download/0343886-200613084148143

**Comment by MortenHofft** [comment]
This looks expected to me, but perhaps I'm misunderstanding.

There are no results matching recordedBy: "%willing%"
https://www.gbif.org/occurrence/download/0343887-200613084148143

Neither are there on the website
https://hp-herbarium-germany.gbif-staging.org/data?filter=eyJtdXN0Ijp7InJlY29yZGVkQnkiOlt7InR5cGUiOiJsaWtlIiwidmFsdWUiOiI%2Fd2lsbGluZz8ifV19fQ%3D%3D&view=TABLE

So that seems reasonable?

**Comment by MortenHofft** [comment]
Ahh - I know see the issue. the `*` maps to `%` . I did that because the download API didn't work that way a month ago. But the issue has been fixed while I was on vacation. I will align with the new behaviour

**Comment by jholetschek** [comment]
Yes... It works on the website, but not in the download.

**Comment by MortenHofft** [comment]
It works now. Thanks for reporting
