### ISSUE TITLE
Increase font size on occurrence and literature pages

### ISSUE THREAD

**Issue by jenningsdt** [gbif/hosted-portals#192]
The font size of the search results on the [`Occurrences`](https://hp-north-america.gbif-staging.org/data?view=TABLE), [`Literature from`](https://hp-north-america.gbif-staging.org/literature/from), and [`Literature about`](https://hp-north-america.gbif-staging.org/literature/about) pages appears small. What is the best way to increase the font size? I am attaching a screenshot of the `Literature from` for reference -- note the size difference between the various menu items and the search results. Thank you!
![image](https://user-images.githubusercontent.com/7525925/136407912-df315086-0137-4407-8068-fd48666af6ed.png)

**Comment by MortenHofft** [comment]
The size is small as a default for the data tables as I have often recieved the feedback that users want dense tables so that they can see as much as possible at a glance. Pretty UIs is almost always very spacious. Either way, changing the theme font size helps I think. If you find it insufficient then let me know, then I can see what else I can come up with. Thanks
