### ISSUE TITLE
Literature pages produce blank screen

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/hosted-portals#195]
For the GBIF North America and GBIF.us portals when you select Literature From the resulting screen is blank. This is also true for GBIF North America literature about. The GBIF.us Publications About does still work. We have tested on multiple computers using both Mac and PC on Chrome and Firefox.

**Comment by MortenHofft** [comment]
It seems that the APIs have changed behaviour.
The website clearly fails very ungracefully. But the underlying issue is the API.

https://api.gbif.org/v1/literature/search?limit=20&offset=0&countriesOfResearcher=US&countriesOfResearcher=CA&countriesOfResearcher=MX&countriesOfResearcher=UM&countriesOfResearcher=PR&countriesOfResearcher=VI&countriesOfResearcher=AS&countriesOfResearcher=GU&countriesOfResearcher=MP

**Comment by MortenHofft** [comment]
I've created an issue for the API bug here https://github.com/gbif/literature-ws/issues/6

**Comment by MortenHofft** [comment]
Thanks @albenson-usgs - I've split the issue into two (API bug and insufficient error handling in the interface) and will close this.

**Comment by MortenHofft** [comment]
I've added some basic error handling for now. The APIs still fail, but at least it isn't just a blank screen, but a message to the user
