### ISSUE TITLE
Document preparation material for the first group call

### ISSUE THREAD

**Issue by timrobertson100** [gbif/hosted-portals#2]
There will be a group call at the end of January, and we should document what attendees can do to prepare for the call. This might include e.g. 

1. Establishing a GitHub account
2. Considering the menu structure of their site (should we provide an example)
3. Finding a logo and colour palette (how many colours?)
4. Preparing text for the static pages of their site
etc

I suggest we put these instructions in a markdown file within this GH so it can be referenced in the future.

**Comment by MortenHofft** [comment]
Here is a suggestion for tasks to start with. Feel free to change anything

## Step 1

**Github**
Your website code and content will live in Github. If you have never heard of Github, then it might be worth finding a small introduction video on youtube or similar.

Put very simply: it is a website https://github.com/ where you can store files and directories and have multiple people working on them. You can have multiple projects (or repositories as they are called) and you can decide who is allowed to edit what information. You can download the whole thing and work locally or you can use a web interface. For what we need, it is fine to work in the web editor.

This is where you will be doing all of your content editing, so it is worth investing time getting familiar with the interface.

* Create a Github account
* Send us the Github usernames that should be able to edit. (by email).

**Data scope**
What is your data scope? Try to build it on https://gbif.org/occurrence/search. If that isn't possible then try to write it using the occurrence download APIs [predicate structure](https://www.gbif.org/developer/occurrence#predicates).
  
**Menu**
* What is in your menu?
* Are there any pages that aren't accessible from the menu? How do the user discover them?
* Try to write the menu structure as YAML (see below)

**Logo**
Do you have a logo? Then find a good digital version. Make sure the background is transparent. ideally a `png` or a `svg`. By default the logo will be 28 px high - meaning it will not work well if it is [very complex](https://qph.fs.quoracdn.net/main-qimg-dabbb24c9503df66c8d1c75642dd61ab).

If you do not have a logo, then the name of your site will be used instead.

**Styling**
You can tweak the look with a few variables. If you need more, then you need to write additional css (please say if you need to, then we might be able to help). The most important theme variables are
* Find a primary color
* and possibly a secondary color for links

Choose a color and write it in HEX code. 
You can use a [color picker/converter](https://www.google.com/search?q=color+picker) to do so

**News items**
Do you have news items/blog posts or similar content that you produce regularly?

**Social media**
Do you have any social media account you would like to link too? which and what are the links/usernames.

**Languages**
Is your site in mulitple languages? Is one language the default (as on https://hp-base-theme.gbif-staging.org/) or is the home page a language selector (as on https://www.cbif.gc.ca/)?

**Domain name**
What is your domain name (the url of your website)? Do you already have one? Do you know how to buy and manage it yourself?

**Footer**
What is in your footer. The footer is many small blocks with a headline and some text below. See https://hp-base-theme.gbif-staging.org/ for an example.

**Learn markdown**
Familiarize yourself with Markdown. Here is an introduction from Github https://guides.github.com/features/mastering-markdown/

**Prepare your first page**
Prepare your first page (the end result will be similar to https://hp-base-theme.gbif-staging.org/about)
* Write text in Markdown (you can use an online editor like https://stackedit.io/)
* Find a background header image
* Write an image caption in markdown
* Optionally: try to create a new repository in Github, create a new file `something.md` and add your text. Notice that Github will format your Markdown.

## Step 2

**Read the Jekyll docs**
This website is created using Jekyll. They have good [documentation](https://jekyllrb.com/docs/pages/) and it is worth reading parts of it. Not everything is important as most of it is for developers. But below sections are relevant:

* Content section: the documentation for `pages`, `posts`, `front matter`, `data files` and `assets` are relevant when editing the site.
* Site structure: https://jekyllrb.com/docs/structure/

**Get familiar with YAML (also known as yml)**
YAML is used a lot when building your website. For defining the menus and to add structured metadata to the individual pages. You are welcome to just copy-paste examples, but it might be a good idea to read [an introduction](https://dev.to/paulasantamaria/introduction-to-yaml-125f)

*Short intro to YAML*
It is a way to write structured data that machines can read. A bit like filling in a form, but you have to write the name of the field as well.
```
title: Fungi of the world
image: http://sitename.com/image/123
caption: "Photo by Morten H. License CC0."
```
Because above is 3 distinct pieces of information (unlike markdown that is one big piece of text), we can do more complex layouts. Such as having the title float on top of the image and have a semi transparent caption in the corner. This is essential for menus, complex page headers, and landing pages like the home page.

**Comment by MortenHofft** [comment]
I've created a file with above text https://github.com/gbif/hosted-portals/blob/main/getting-started/preparation.md
