### ISSUE TITLE
stories are not appearing in prod

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#296]
Hi,

I just noticed that the Data Use stories are not appearing in prod: 
- https://www.biodiversity.aq/

<img width="1078" alt="Screenshot 2024-06-24 at 16 10 38" src="https://github.com/gbif/hosted-portals/assets/11754081/7fc541e9-2a7e-4529-b930-85c9f683aa3a">

But it is working fine in staging:
- https://hp-antarctic.gbif-staging.org/

<img width="1180" alt="Screenshot 2024-06-24 at 16 10 19" src="https://github.com/gbif/hosted-portals/assets/11754081/86e0e74b-5dbe-42c9-a571-cd5281262eb3">

I am not sure what I missed. Can you please advise? Thanks a lot!

**Comment by MortenHofft** [comment]
It's not you - it's me.

I updated graphql to have a stricter schema the other day. And updated the hosted portal theme to match it. And since staging has been rebuild since it looks fine, but production haven't been rebuild so it is using the previous version of the theme. 
I normally account for that, but completely forgot that this time. You either need to do a release again. Or I will have to find a way to redeploy your last release with the new theme. Is your staging site in a state where we can do a release? 
I sorry for the trouble!

**Comment by ymgan** [comment]
Thank you Morten, and no worries at all! I have just made a release and things are fine now :)

I copied the idea from GBIF USA's hosted portal, so maybe they would need a release as well: https://www.gbif.us/stories/
