### ISSUE TITLE
map in dashboard is not updated according to search parameters 

### ISSUE THREAD

**Issue by ymgan** [gbif/hosted-portals#297]
I searched for myctophidae in our hosted portal. Everything else seems to be updated at the dashboard but the map. It keeps returning all occurrences in the hosted portal. Can you please have a look at this? Thank you so much!!

Dashboard url:
https://www.biodiversity.aq/occurrence/search/?layout=W1t7ImlkIjoiZm92b2siLCJwIjp7fSwidHJhbnNsYXRpb24iOiJzZWFyY2gudGFicy5tYXAiLCJyIjp0cnVlLCJ0IjoibWFwIn0seyJpZCI6Im5nd2pwIiwicCI6eyJ2aWV3IjoiVElNRSJ9LCJ0IjoieWVhciJ9XSxbeyJpZCI6InRhdHVwIiwicCI6e30sInRyYW5zbGF0aW9uIjoic2VhcmNoLnRhYnMuZ2FsbGVyeSIsInIiOnRydWUsInQiOiJnYWxsZXJ5In0seyJpZCI6ImI5amY3IiwicCI6e30sInRyYW5zbGF0aW9uIjoiZGFzaGJvYXJkLnRheGEiLCJ0IjoidGF4YSJ9XV0%3D&q=myctophidae&view=DASHBOARD

Screenshot
![Screenshot 2024-08-09 at 09 27 09](https://github.com/user-attachments/assets/4314d0a7-7a32-42d0-8f95-c12ed731fa34)

**Comment by MortenHofft** [comment]
argh you are right. And not just in the dashboard but in the maps as well. That bug has been there all along. Free text only worked for mapbox maps, but since that is what everyone but the Antarctic site is using, then no one noticed. 

It is a tiny fix. I'm deploying to staging now and if it looks good I will put it in prod. It should be available in 15 minutes or so.

**Comment by ymgan** [comment]
thank you so much Morten!!

**Comment by ymgan** [comment]
I just wanted to come back to say that it's really so nice of you to develop this just for us despite the extra work of maintenance, we really appreciate it!
