### ISSUE TITLE
Dataset template

### ISSUE THREAD

**Issue by siwelisabeth** [gbif/hosted-portals#31]
The LivingNorway team would like to request a dataset template, i.e a landing page inside the hosted portal for a dataset. This page can be used to describe and visualize the dataset and can be customized by the different projects. This will be an alternative to just a link to the GBIF dataset page.

**Comment by MortenHofft** [comment]
I think I agree, but I'm not entirely sure what you mean (I'm not even sure what I think is the correct approach either).

Could you describe the idea a bit more please?

-----

Currently we do not have a dataset page as such - instead we have information about a given dataset in a slide-in drawer. As in the image below.

There are many things we could do
* just make them linkable (as in `/data?view=dataset&detail=datasetKey:123`)
* linking to it from the occurrence record?
* Having dedicated dataset urls a la `living-norway.no/dataset/123`
* somehow make the dataset drawer/dedicated page more stylable.

Making it customisable will make the project more complex and will for most likely require a developer in your end. What kind of customisation do you imagine? 

I can imagine multiple ways to customise them. The most flexible would be to link to a url of your liking and then you develop that page entirely on your own. Then if you do not like below, then you could easily replace it, but it would then fall on you/your developer to maintain that dataset page.

<img width="1440" alt="Screenshot 2021-03-01 at 09 49 23" src="https://user-images.githubusercontent.com/6759267/109473546-b6b3da80-7a73-11eb-9c8b-3e7eb56f6462.png">

**Comment by dagendresen** [comment]
In Living Norway, we expect that the entire dataset will be the unit of interest to most users. The sampling protocol etc will (most often) be the same for all data records inside the dataset. The researcher would most often assess fitness for use of the dataset (and normally not for each individual record).

Portal functionality for listing and filtering datasets and a detail page for each dataset would very often be much more valuable than the list and filter for individual occurrences.

PS: We have communicated this portal requirement in all hosted portal workshop and also in the application for the Living Norway hosted portal :-)

**Comment by timrobertson100** [comment]
Thanks @dagendresen @siwelisabeth 

The wish for showing the dataset detail is clear, and it is expected to have dataset search in the future.

What I understood from @MortenHofft is that it is unclear what was meant by this:

> and can be customized by the different projects 

Can you elaborate on how you envisage customizing them, please @siwelisabeth? Or is the request really to have the equivalent of what is shown on a dataset page on GBIF.org?

**Comment by dagendresen** [comment]
I believe that Living Norway is exploring additional dataset metadata in addition to the EML -- maybe in a Frictionless data format (as Andre Heughebart has proposed) -- or maybe in a standardized Markdown data-format (?). And that such additional dataset metadata might be included into the Darwin Core archive -- or preferably linked to from one of the EML terms (?). And that the feature-wish is for using some own developer time to extend the dataset metadata model with data from such extensions. (@siwelisabeth might want to correct my description)

**Comment by siwelisabeth** [comment]
It would be nice if the template could come with an example, i.e fetching a test dataset and display some information about it in a page. The page could have a couple of sections that could be used to show various information about the dataset. So I was thinking more customization of layout, i.e that the template could be a starting point for creating a "dataset landing page". But I also agree with @dagendresen that extending the dataset metadata model could be useful in this page.

**Comment by ErlendNilsen** [comment]
Thanks @timrobertson100 @MortenHofft for quick response to our request! I think using somthing similar (or a simplified version) to the dataset view on gbif.org (with some possibility to customize content and branding - if possible) would be great. If possible, it could include i) data download option, ii) EML metadata, iii) data citation tracking. The possibility to add additional metadata as @dagendresen mention might be a future wish. In Living Norway we will also explore ways to display/visualize event based data further, so perhaps some of that could be implemented in the future?  Having dedicated dataset urls a la "living-norway.no/dataset/123" would be fantastic!

**Comment by jocelynpender** [comment]
@MortenHofft Could you provide an example or documentation on how a custom dataset could be displayed on the hosted portals? I just want to get an idea of how much work it would be to create something and maintain it. This will help us to discuss with our management what we want to do with the hp.
There are several datasets/tools on the current CBIF that will be going "dark" this summer (aka. they will die and will no longer be accessible online). We want to know if we could migrate them to the hosted portal. 
See [this page](https://www.cbif.gc.ca/eng/species-bank/?id=1370403266204) for the tools in question.

**Comment by MortenHofft** [comment]
I'm not sure how to comment on this issue. I read it as if everyone mean/ask something different.

**First iteration**
* to create a Jekyll theme that allowed participants to write prose about their work (mostly done)
* have an data widget to explore occurrences (mostly done)
* All other data types would be visible via GBIF.org

**Future work**
In time we will expand data types to include:
* data set search and dataset pages
* publisher search and publisher pages
* and more content types

Search will be similar in appearance to the occurrences search.
And detail pages (individual dataset and publisher pages) would have their own URL on the hosted portals. And would like GBIF.org allow for downloading the source archive and the EML. And it will include citations and list of downloads. Essentially be the same as the dataset/publisher pages on GBIF.org.

**Custom dataset/publisher pages**
In addition I've been pondering if we could somehow allow urls for detail pages to be overwritten - meaning that a site owner could create their own dataset page if they weren't happy with the GBIF style ones. I believe that should be fairly easy to allow in some format. But it would put the responsibility to do so entirely on the site owners. So it wouldn't extend them. It would overwrite them.

How you choose to do so would be out of our control. You can use whatever framework you like. Use GBIF APIs or build your own. Turn the cursor into a butterfly. Anything within the constraints of Jekyll. Which is quite wide, the main constraint is that search engines might not index you properly.

**Custom tools**
Same story for custom tools (you can do those now)
Essentially you just add a custom `layout` or custom `include` and use those.
https://jekyllrb.com/docs/layouts/ What you do there is up to the imagination of your developer. Because this is just a Jekyll site then there isn't really any constraints enforced by this project.

**Caveat**
The more custom developer work you do, the more I would recommend that you found another solution than the hosted portals. At some point it will feel more like a constraint to use the Jekyll theme.

**Comment by MortenHofft** [comment]
Here is an example for how one can add a custom dataset page using the GBIF API.
https://hp-theme.gbif-staging.org/example/dataset?key=492d63a8-4978-4bc7-acd8-7d0e3ac0e744

This is just a crude example and is by no means intended as a production ready solution.

**Comment by MortenHofft** [comment]
The work on dataset pages have started and [can be seen here](https://react-components.gbif-staging.org/iframe.html?id=entities-dataset-page--example&args=&viewMode=story). It is work in progress so this isn't a request for feedback but to be transparent about the work going on.

**Comment by siwelisabeth** [comment]
This looks very nice :-) When do you think this component will be available for the hosted portals?

**Comment by MortenHofft** [comment]
@siwelisabeth I plan to have a first version ready in this next phase. So 6 weeks roughly. It wont have everything that dataset on GBIF.org have (e.g. metrics), but my impression is that less also have value. You could still have your own search/collections and then link to these instead.

But I was under the impression that you had custom needs and was building your own for that reason?

**Comment by siwelisabeth** [comment]
@MortenHofft Yes, you are right, we have some custom needs, so we will probably stick with our own. But it looks good and very similar to what we want to build :-)

**Comment by MortenHofft** [comment]
I would like to understand to which extent we could be working together on e.g. dataset pages.
See also this [request for contributions to the publisher pages](https://github.com/gbif/hosted-portals/issues/170)

@siwelisabeth and @frafra I know that you are working on your own version of a dataset page. I'm curious to learn more about your needs. Could you possibly describe what you need? And if you have ideas to how dataset pages could be extended in a generic way that ideally isn't specific to your use case.

**Comment by siwelisabeth** [comment]
The first version of dataset pages we are developing uses the GBIF api to create a dataset page in our portal. We also want to enrich the dataset page with information from other sources, i.e show information about the project that the dataset belongs to. I think that our team members also have more ideas and thoughts for our dataset pages for the future. It would be nice to arrange a meeting with you and some of the team members here, i.e @frafra and @ErlendNilsen and myself. Right now it is vacation time and most of us are out of office in July. I suggest that we meet in August to discuss this further.

**Comment by MortenHofft** [comment]
The dataset page has been sitting quite 90% done for ages. I have now released a version to production. It still need work to have feature parity with gbif.org, but it is better than nothing for those that are intersted in a dataset page that do not, unlike "living norway", have capacity to write their own.

Example https://hp-theme.gbif-staging.org/dataset/19fe96b0-0cf3-4a2e-90a5-7c1c19ac94ee
