### ISSUE TITLE
Document a getting started for authors

### ISSUE THREAD

**Issue by timrobertson100** [gbif/hosted-portals#5]
Create a simple `Getting started for authors` as a MD file in this repository, capturing the very basic things for a new HP author. I could imagine for example the following sections as being sufficient:

1. Changing your color
2. Changing the logo
3. Creating a page (do we need different page types perhaps?)
4. Linking your new page in the menu
5. Adding an external link in your menu

**Comment by MattBlissett** [comment]
An explanation of what is in the repository (7 folders etc) might be a good introduction.

> If your logo is online already then you can simply refer to that url.

Only if it's HTTPS, otherwise there's a warning, and I think I'd recommend copying it to the assets anyway -- hotlinking from an institutional website will inevitably break.

> Create a file hello.md with the following content

Where? I think you might need to explain the difference between pages in the root of the repository, and the contents of _posts.

**Comment by MortenHofft** [comment]
Thank you Matt. 

It is a good idea to suggest a place to create that file.

Other than that I'm a bit reluctant to explain things that is explained better in the Jekyll documentation. Examples being: what is a page and how does it work with folders. That is why I start that task with a link to [the documentation on pages](https://jekyllrb.com/docs/pages/) and ask the user to spend 2 minutes reading that.

**Comment by MortenHofft** [comment]
There is a limit to how simple we can make this, if the editors are to edit files themselves then they need to learn a bit about Jekyll, yaml etc. If we really believe it should be simpler, then we could integrate with something like Contentful and have that as an editor platform.
