### ISSUE TITLE
Behavior for opening news items is confusing

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/hosted-portals#54]
Ideally I'd like to be able to click anywhere on the "card" to open the news item. However for some of the hosted portals I've looked at you have to click the title of the news item to open it up. On the BISON hosted portal you can also click on the image as well as the title and the news item opens up (at least for me on Chrome, Windows) but this functionality is not there in other hosted portals I've tested (like GBIF-NA and SPREP). 

1. Can we make the cards so you can click anywhere in the news item and it opens up the full post?
2. If not, is there a way to change the title color to make it more obvious to users that you click the title of the news item to open the full post?

**Comment by MortenHofft** [comment]
The way we display images was recently changed. This was done to reduce images sizes. A part of that exercise was to rewrite all image usage. In that process the image link was lost. That was fixed afterwards. But websites that haven't had any changes since still have the previous behaviour. So when those sites are edited, the fix will show on those sites as well. I can  deploy the NA website now :)

As for changing link color for headlines, then https://github.com/gbif/hp-north-america/blob/master/_config.yml#L51 should be what you are looking for.

**Comment by MortenHofft** [comment]
The use of images was changed from just using the provided image as uploaded, to instead scale it to various device sizes and automatically detect what to load when 

And secondly to convert the image to `webp` and  `jpg` and use the smallest when the browser supports it. This will in many cases dramatically reduce images sizes for mobile devices (say 1/10 of the size or so)
